sudo: false
dist: trusty
git:
  depth: false

language: java
jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - graphviz

cache:
  directories:
    - $HOME/.m2/repository

before_install:
  # copy maven settings
  - cp .travis/mvn-settings.xml $HOME/.m2/settings.xml
  - cp .travis/mvn-toolchains.xml $HOME/.m2/toolchains.xml
  # import the GPG secret keys and owner trust
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
  # allocate commits by travis to the CI user
  - git config user.name "Talsma CI"
  - git config user.email "ci-user@talsma-ict.nl"
  # setup https authentication credentials for github, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  - ./mvnw --version

script:
  - .travis/scripts/build.sh
  - .travis/scripts/release.sh

after_success:
  - if [ -f target/jacoco.exec ]; then ./mvnw jacoco:report coveralls:report; fi

deploy:
  provider: releases
  name: Release $TRAVIS_TAG
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - ./**/target/umldoclet-*.jar
    - ./**/target/umldoclet-*.jar.asc
  skip_cleanup: true
  on:
    tags: true
