#sudo: required
sudo: false
dist: trusty
#group: edge
jdk: oraclejdk9

language: java
#jdk:
#- oraclejdk8

addons:
  apt:
    packages:
#    - oracle-java9-installer
    - graphviz

cache:
  directories:
  - $HOME/.m2/repository

before_install:
  # import the GPG secret keys and owner trust
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi
  # allocate commits by travis to the CI user
  - git config user.name "Talsma CI"
  - git config user.email "ci-user@talsma-ict.nl"
  # setup https authentication credentials for github, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  # copy maven settings
  - cp .mvn/settings.xml $HOME/.m2/settings.xml
  - cp .mvn/travis-toolchains.xml $HOME/.m2/toolchains.xml

install:
  # use the maven wrapper instead of provided maven
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - .travis/publish.sh

branches:
  except:
    - /^[0-9]/
